### ISSUE TITLE
great software bro but where is the password 

### ISSUE THREAD

**Issue by ghost** [netcan/baike_contest#1]
thank's

**Comment by netcan** [comment]
you can see my database file: [baike_contest.sql#L54](https://github.com/netcan/baike_contest/blob/master/baike_contest.sql#L54)，the user's password will be plaintext stored in `password` column.

**Comment by netcan** [comment]
By the way, It didn't support login function, you could import `bake_contest.sql` into database first, then insert some user's information such as password, id to `profile` table.

**Comment by netcan** [comment]
One thing to note is that `profile` table's `id` column is user login id, in other words, in login page(it's home page), the `学号` is `profile` table's `id`。

**Comment by ghost** [comment]
I DO IT BRO BUT WHEN I LOGIN IN CHINSES 40 MINUTE DON'T SEE THE QUESTION !! 
AND I UPLOAD THE DATABASE AND I SET THE USERS CORECTLY EVREY THINK FINE AND I DON'T SEE THE QUESTION AGAIN :+1:  :100:  THANK'S MAN

**Comment by netcan** [comment]
does `question` table have questions？

**Comment by ghost** [comment]
yes

2016-08-15 3:50 GMT+01:00 Netcan notifications@github.com:

**Comment by netcan** [comment]
I will check it soon

**Comment by ghost** [comment]
TTHANK'S

2016-08-15 4:20 GMT+01:00 Netcan notifications@github.com:

**Comment by netcan** [comment]
I have fixed it, now no problems.

**Comment by ghost** [comment]
thannnnnk's man

2016-08-15 5:09 GMT+01:00 Netcan notifications@github.com:

**Comment by netcan** [comment]
no problem.
