### ISSUE TITLE
学长！

### ISSUE THREAD

**Issue by shenlebantongying** [netcan/baike_contest#2]
为什么不把这个程序扩展成一个通用的刷题工具呢？

就像我们用的思政课什么的，只要加上一部分错误的题再次出现的代码就好。

棒！

**Comment by netcan** [comment]
这个程序大一写的，但是就是针对竞赛设计的，后面就不在维护了

**Comment by shenlebantongying** [comment]
感觉你们宣城校区的计算机专业学生比这边好多了。

话说，我的大一快结束了，我也要写一个这样的稍微大型的程序，
